openapi: 3.0.1
info:
  title: Mem0 API Docs agents apps API
  description: mem0.ai API Docs
  contact:
    email: support@mem0.ai
  license:
    name: Apache 2.0
  version: v1
servers:
- url: https://api.mem0.ai/
security:
- ApiKeyAuth: []
tags:
- name: apps
paths:
  /v1/apps/:
    post:
      tags:
      - apps
      description: Create a new App.
      operationId: apps_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateApp'
        required: true
      responses:
        '201':
          description: App created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateApp'
      x-codegen-request-body-name: data
components:
  schemas:
    CreateApp:
      required:
      - app_id
      type: object
      properties:
        app_id:
          title: App id
          minLength: 1
          type: string
        name:
          title: Name
          minLength: 1
          type: string
        metadata:
          title: Metadata
          type: object
          properties: {}
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'API key authentication. Prefix your Mem0 API key with ''Token ''. Example: ''Token your_api_key'''
x-original-swagger-version: '2.0'
